all: default

default:
	javac MIPS/MIPS.java
	java MIPS/MIPS inst.txt data.txt config.txt result.txt

ex1:
	javac MIPS/MIPS.java
	java MIPS/MIPS inst1.txt data.txt config.txt result.txt

ex2:
	javac MIPS/MIPS.java
	java MIPS/MIPS inst2.txt data.txt config.txt result.txt

ex3:
	javac MIPS/MIPS.java
	java MIPS/MIPS inst3.txt data.txt config.txt result.txt