all: default

default:
	javac MIPS/MIPS.java
	java MIPS/MIPS inst.txt data.txt config.txt result.txt

1:
	javac MIPS/MIPS.java
	java MIPS/MIPS inst1.txt data.txt config.txt result.txt

2:
	javac MIPS/MIPS.java
	java MIPS/MIPS inst2.txt data.txt config.txt result.txt

3:
	javac MIPS/MIPS.java
	java MIPS/MIPS inst3.txt data.txt config.txt result.txt